### ISSUE TITLE
Collaborators toevoegen

### ISSUE THREAD

**Issue by marcvanandel** [kadaster-labs/solid-quest-mock-overheid-server#3]
Ik zou hier graag een PR willen maken ... @kad-busses , wil je mij toevoegen als collaborator? 😁

**Comment by kad-busses** [comment]
Kun jij een Solid-Quest team aanmaken binnen kadaster-labs? Kan ik het hele team in 1x toegang geven 😉

**Comment by marcvanandel** [comment]
Nee, dat kan ik niet 😞 'k Zal 's vragen in het #dev channel ...

**Comment by kad-busses** [comment]
Je hebt nu toegang
